package mri.advent.y2024.day08

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class Day08Test {

    private val sample = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
    """.trimIndent()

    @Test
    fun testPartOne() {
        assertEquals(14, Day08(sample).partOne())
    }
    @Test
    fun testPartTwo() {
        assertEquals(34, Day08(sample).partTwo())
    }



    @Test
    fun simpleTest() {
        val simple = """
..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
..........
        """.trimIndent()
        assertEquals(2, Day08(simple).partOne())

        assertEquals(5, Day08(simple).partTwo())
    }

    @Test
    fun simpleTest2() {
        val part2 = """
T....#....
...T......
.T....#...
.........#
..#.......
..........
...#......
..........
....#.....
..........
        """.trimIndent()
        assertEquals(9, Day08(part2).partTwo())
    }

}
